<?php
/**
	The following settings values are to be edited according
	to the user preferences. This file sets all parameters 
	needed to run WhatsAPI successfully. 
	NOTE: ONLY this file needs to be edited to use WhatsAPI. Please
	do not modify any other file in the WhatsAPI directory.
    

    Database connection settings.
    These settings are used to login to the database to log incoming/inbound
    messages downloaded from WhatsAPI servers.
    NOTE: These values MUST be EXACTLY the SAME as the MsgApp database configuration
    settings. These settings should be set AFTER setting up MSgApp, as BOTH the MsgApp
    and WhatsAPI module share the same database.
    1. $db_name : The name of the database, as set previously in MsgApp.
    2. $db_user : The database username, as prevoiusly set in MsgApp.
    3. $db_pass : The database password, as previously set in MsgApp.
    4. $db_host : The database host, as previously set in MsgApp.
**/
$db_name = "msgapp";
$db_user = "";
$db_pass = "";
$db_host = "192.168.101.249";
/**
	After setting the database values, you will need to:
		1. Start your web server (Xamp or Wamp), then launch your browser.
		2. Load http://localhost/whatsapi/db/class.db.php
	If the browser responds with "Conn Ok", the configuration is successful,
	otherwise use the error message to figure out the problem.
	WhatsApp Settings.
	 These settings are required by WhatsAPI script to login successfully to WhatsApp servers.
	 1. $whatsapp_phone    : Phone No. that was used to create/register a WhatsApp account.
	 2. $whatsapp_identity : This is the IMEI of the equipment/Phone that was used 
	 						 to register WhatsApp account.
	 3. $whatsapp_name	   : WahtsApp profile name.
	 4. $whatsapp_pass	   : WhatsApp password, which was either generated by Wart Tool or
	 						 sniffed from device, or obtained in whichever method.
	 5. $whatsapp_debug    : true, unless otherwise. This determines if to display debug messages
	 						 from WhatsApp or not. It should be left as it is i.e. true.
 **/
$whatsapp_phone    = '254711714306'; 
$whatsapp_identity = '351737052166495';
$whatsapp_name     = 'chief'; 
$whatsapp_pass     = 'm58/He9kWcbB6iYvqFbrsW6z2kY='; 
$whatsapp_debug    = true;

/**
	After setting the whatsapp values, you will need to:
		1. Start your web server (Xamp or Wamp), then launch your browser.
		2. Load http://localhost/whatsapi/run/class.whatsapp.php
	If the browser sholud respond with no output message, or should display any message
	that has ben sent to above number, and ut has not been seen yet. If you recieve errors
	please consult admin.
**/